edition = "2024"
fn_params_layout = "Tall"
force_explicit_abi = true
hard_tabs = false
hex_literal_case = "Upper"
match_arm_leading_pipes = "Always"
match_block_trailing_comma = false
max_width = 128
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
short_array_element_width_threshold = 0
style_edition = "2024"
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
